-- TABLA USERS
create table public.users (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text,
  name text,
  cedula text not null,
  phone text,
  role text default 'patient'::text,
  type text,
  notes jsonb,
  registered_at timestamp with time zone default timezone('utc'::text, now())
);

-- Indices y Restricciones para Users
create unique index users_cedula_key on public.users (cedula);
create unique index users_email_key on public.users (email);

-- TABLA APPOINTMENTS
create table public.appointments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_name text,
  patient_cedula text,
  date_str text,
  time text,
  type text default 'Cita'::text,
  status text default 'PENDIENTE'::text,
  color text default 'bg-orange'::text,
  notes text 
);

-- Indices para Appointments
create index appointments_date_str_idx on public.appointments (date_str);
create index appointments_patient_cedula_idx on public.appointments (patient_cedula);

-- POLITICAS DE SEGURIDAD (RLS)
-- Habilitar RLS
alter table public.users enable row level security;
alter table public.appointments enable row level security;

-- Permitir acceso público (lectura/escritura) para que funcione con la Public Anon Key
-- NOTA: En producción, deberías restringir esto más.
create policy "Enable read access for all users" on public.users for select using (true);
create policy "Enable insert access for all users" on public.users for insert with check (true);
create policy "Enable update access for all users" on public.users for update using (true);
create policy "Enable delete access for all users" on public.users for delete using (true);

create policy "Enable read access for all appointments" on public.appointments for select using (true);
create policy "Enable insert access for all appointments" on public.appointments for insert with check (true);
create policy "Enable update access for all appointments" on public.appointments for update using (true);
create policy "Enable delete access for all appointments" on public.appointments for delete using (true);
